### ISSUE TITLE
Notify users about deprecation

### ISSUE THREAD

**Issue by RVFET** [surfinzap/b-theme-vscode#13]
Love the theme, but I got heart attack seeing my vscode looks default after restarting it. I though I somehow screwed my settings, luckily it was just Bikkuri theme being deprecated.

I opened this issue because there was no notification, message, output or anything about the old extension getting deprecated and new one being added. I clicked on the developer name on VSCode Extensions tab and found about the new one, perhaps it'd be better to somehow let the users know.

**Comment by surfinzap** [comment]
@RVFET Thanks for your support! I left a deprecation notice at [previous marketplace URL](https://marketplace.visualstudio.com/items?itemName=brano.b-theme). However, leaving the notification in a few other places might be useful. What was the first place you were looking at?

**Comment by surfinzap** [comment]
The deprecation notice and link are now also included when opening the previous extension in VS Code Extensions:
![image](https://github.com/surfinzap/bikkuri-theme-vscode/assets/1387798/4dc3d467-b87b-40e1-a418-fe73fa74cf6f)
