### ISSUE TITLE
Theming issue on keyboard shortcuts page

### ISSUE THREAD

**Issue by TheLastZombie** [surfinzap/b-theme-vscode#17]
Beautiful themes, thank you!

I noticed that there is an issue with the keyboard shortcuts page (*File -> Preferences -> Keyboard Shortcuts* in the menu or *Preferences: Open Keyboard Shortcuts* from the command palette):

![image](https://github.com/surfinzap/bikkuri-theme-vscode/assets/8181990/0a87ae7b-6ef1-4546-b1ce-3cd86a134862)

(The screenshot was taken with version 6334a87b8b8e02a16e8498773653b2ca42555db0 and the *Warm & Serene* variant, but the issue persists with the other variants as well.)

**Comment by surfinzap** [comment]
Thanks, @TheLastZombie, for reporting the issue. I've just released the new version (1.0.4) with the fixed rows. It should be available in the VS Code as well.
